spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:${DB_FILMES_PORT:5434}/${POSTGRES_DB:db_filmes}
    username: ${POSTGRES_USER:root}
    password: ${POSTGRES_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show_sql: true
    defer-datasource-initialization: true